#! /bin/sh
# /etc/init.d/agent-automation
### BEGIN INIT INFO
# Provides: agent-automation
# Required-Start: $all
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: agent automation
### END INIT INFO 
case "$1" in
  start)
    echo "Starting agent-automation"
    # run application you want to start
     python3 /agent/agent.py -L -ina -esi 193.106.55.141:2241 -esp /home/elk/logstash/files -esup elk:bartar@401@cs -op /tmp/test -tn 3 -ra

#    echo "bye" > /home/hello22.txt
    ;;
  stop)
    echo "Stopping agent-automation"
    # kill application you want to stop
    echo "bye" > /home/test/Desktop/hello22.txt
    ;;
  *)
    echo "Usage: /etc/init.d/agent-automation{start|stop}"
    exit 1
    ;;
esac
 
exit 0
